AllCops:
  TargetRubyVersion: 2.7
  Exclude:
    - bin/**/*
    - config/**/*
    - db/**/*
    - node_modules/**/*
    - test/**/*
    - tmp/**/*
    - vendor/**/*

Style/Documentation:
  Exclude:
    - app/**/*

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 15

Lint/RaiseException:
  Enabled: true
Lint/StructNewOverride:
  Enabled: true
Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true
Layout/SpaceAroundMethodCallOperator:
  Enabled: true
Style/ExponentialNotation:
  Enabled: true
